services:
  postgres:
    image: postgres:17
    container_name: medical_booking
    environment:
      POSTGRES_DB: medical_booking
      POSTGRES_USER: medical_booking
      POSTGRES_PASSWORD: password1234
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: